"""empty message

Revision ID: ddf2c5d9ede6
Revises: 359087295031
Create Date: 2024-01-12 20:34:56.613806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddf2c5d9ede6'
down_revision = '359087295031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('lap_splits', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('top_speed', sa.Float(), nullable=False),
    sa.Column('place_finished', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['base_game_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('base_game_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('time_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('high_score',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'base_game_data', ['game_id'], ['id'])
        batch_op.drop_column('place_finished')
        batch_op.drop_column('lap_splits')
        batch_op.drop_column('top_speed')
        batch_op.drop_column('play_duration')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('date_added',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('date_added',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('base_game_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('play_duration', postgresql.INTERVAL(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('top_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lap_splits', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('place_finished', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('high_score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('time_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('game_id')

    op.drop_table('racer')
    # ### end Alembic commands ###
